spring.application.name=JavaURL
server.port=8080

# Data Source
spring.datasource.url=jdbc:postgresql://javaurl.ca58aa0akjx5.us-east-1.rds.amazonaws.com/postgres
spring.datasource.username=postgres
spring.datasource.password=I>MILm8r?DE:?-U.WK*BAE9fH_gp

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
logging.level.org.flywaydb=DEBUG